[mcrecover] CMakeLists: Reorder target link libraries: zlib/png before Qt.
My copy of Qt/shared has its own built-in copy of zlib.
Due to the way the import definitions are set up in libQtCored4.a,
if zlib isn't linked before Qt, it results in a linker error due
to multiple definitions of _zlibVersion:

../../extlib/zlib/libzlibstatic.a(zutil.obj): In function `zlibVersion':
/home/david/programming/mcrecover/extlib/zlib/zutil.c:31: multiple definition of `zlibVersion'
/usr/i686-w64-mingw32/qt-4.8.5/shared/lib/libQtCored4.a(d004777.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status