[mcrecover] McRecoverWindow: Use a C string for the variable, not a QLatin1String.
This didn't work in the travis-ci build:

/home/travis/build/GerbilSoft/mcrecover/src/mcrecover/windows/McRecoverWindow.cpp:964:16: error:
      no matching constructor for initialization of 'QLatin1String'
        QLatin1String className;
                      ^
/usr/include/qt5/QtCore/qstring.h:89:38: note: candidate constructor not viable:
      requires single argument 's', but no arguments were provided
    Q_DECL_CONSTEXPR inline explicit QLatin1String(const char *s) : m_si...
                                     ^
/usr/include/qt5/QtCore/qstring.h:91:21: note: candidate constructor not viable:
      requires single argument 's', but no arguments were provided
    inline explicit QLatin1String(const QByteArray &s) : m_size(int(qstr...
                    ^
/usr/include/qt5/QtCore/qstring.h:86:7: note: candidate constructor (the
      implicit copy constructor) not viable: requires 1 argument, but 0 were
      provided
class QLatin1String
      ^
/usr/include/qt5/QtCore/qstring.h:86:7: note: candidate constructor (the
      implicit move constructor) not viable: requires 1 argument, but 0 were
      provided
/usr/include/qt5/QtCore/qstring.h:90:38: note: candidate constructor not viable:
      requires 2 arguments, but 0 were provided
    Q_DECL_CONSTEXPR inline explicit QLatin1String(const char *s, int sz...
                                     ^
1 error generated.